#ifndef TRANSFERENUM_H
#define TRANSFERENUM_H

enum TransferEnum{
    LOGINING=0,
    GETMAINPAGE=1,
    GETCOURSECOMPONENTS=2,
    GETTESTQUESTION=3,
    SETNEWGROUP=4,
    SETNEWTEST=5,
    SETNEWCOURSE=6,
    RECONECT=7,
    GETINFOFORADDINGPOTOK=8,
    SETNEWPOTOK=9,
    GETINFOFORADDINGGROUP=10,
    GETINFOFORAADDINGCOURSE=11,
    GETINFOFOREDITGROUP=12,
    GETGROUP=13,
    UPDATEGROUP=14,
    GETALLCOURSECOMPONENTS=15,


    GETMARKS=16,
    UPDATECOURSECOMPONENTS=17,
    UPDATETESTQUESTIONS=18,
    UPDATECOURSE=19,
};

enum TypeMessage{
    JSONMESSAGE=1,
    REQUESTFILEMESSAGE=2,
    SENDFILEMESSAGE=3
};

#endif // TRANSFERENUM_H
