#ifndef TRANSFERENUM_H
#define TRANSFERENUM_H

<<<<<<< HEAD
enum TransferEnum{
    LOGINING=0,
=======
enum EnumRoles{
    LOGIN=0,
>>>>>>> 2b2368b (added db manager)
    GETMAINPAGE=1,
    GETCOURSECOMPONENTS=2,
    GETTESTQUESTION=3,
    SETNEWGROUPSTUDENTS=4,
    SETNEWTEST=5,
    SETNEWCOURSE=6,




    GETMARKS=7,
    UPDATECOURSECOMPONENTS=8,
    UPDATETESTQUESTIONS=9,
    UPDATECOURSE=10,
    GETPDF=11
};


#endif // TRANSFERENUM_H
